version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - .db_data:/var/lib/postgresql
    ports:
      - 54321:5432

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python3 main.py
    restart: always
    env_file:
      - ./.env
    ports:
      - 8000:5000
    volumes:
      - ./backend/:/usr/backend/
    depends_on:
      - db

