"""empty message

Revision ID: 2f74ffa3921a
Revises: 591216a41b69
Create Date: 2022-07-21 17:45:13.852969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f74ffa3921a'
down_revision = '591216a41b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('test', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
