"""empty message

Revision ID: a661e35c13ff
Revises: ffb96a6cea4d
Create Date: 2022-07-21 18:42:46.324375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a661e35c13ff'
down_revision = 'ffb96a6cea4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('name', sa.String(length=120), nullable=False))
    op.drop_column('breeds', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('breeds', 'name')
    # ### end Alembic commands ###
